name: Python Script Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_python_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Or any version you want

      - name: Install dependencies
        run: |
          pip install pandas matplotlib seaborn numpy

      - name: Run Python script
        run: |
          python data_cleaning_analysis.py
          
